CREATE DATABASE YTF_DB DEFAULT CHARACTER SET utf8;
USE YTF_DB;
CREATE TABLE tuser
(
  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(255),
  LOGIN_PASSWORD VARCHAR(255)
);
CREATE UNIQUE INDEX TUSER_LOGIN_NAME_uindex ON tuser (LOGIN_NAME);